server:
  # 启动端口
  port: 8086
  servlet:
    # 项目访问根路径
    context-path: /ma
spring:
  application:
    # 项目名称(注册中心注册时使用该名称，应用之间名称不要相同)
    name: vecter-manage-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    dynamic:
      primary: szzh_bbzjcx
      datasource:
        szzh_bbzjcx:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/szzh_bbzjcx?useSSL=false&serverTimezone=UTC
          username: root
          password: "4568357"
        szzh_bbzj:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/szzh_bbzj?useSSL=false&serverTimezone=UTC
          username: root
          password: "4568357"
  #配置hikari连接池
  hikari:
    minimum-idle: 2
    maximum-pool-size: 16
    connection-timeout: 10000
    idle-timeout: 3000
    connection-test-query: select 1
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2:7b
      options:
        temperature: 0.7
        top-p: 0.95
        top-k: 50

  cloud:
    getway:
        routes:
            - id: vecter-manage-service
              uri: lb://vecter-manage-service
              predicates:
                - Path=/ma/**
